name: assesment
description: Assesment portal

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  scoped_model:
  multi_media_picker:
  video_player:
  chewie:
  image_picker:
  path_provider:
  path:
  location:
  intl:
  permission:
  sqflite:
  firebase_core:
  firebase_storage:
  firebase_analytics:
  background_fetch:
  android_alarm_manager:



dev_dependencies:
  flutter_test:
    sdk: flutter


  font_awesome_flutter: ^8.0.1

flutter:

  uses-material-design: true

  assets:
      - assets/login_logo.png
      - assets/img/placeholder.png
      - assets/img/video_player.png
      - assets/img/loading.gif

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
